const fs = require('fs');
const response = JSON.parse(fs.readFileSync('./helpers/chatbot/response.json'));

// Function to manage custom intents are defined here
module.exports = {
    CheckMalariaSymptoms: function(parameters, done) {

        const symptomScores = {
            chills: 2,
            fatigue: 2,
            fever: 2,
            malaise: 2,
            shivering: 2,
            sweating: 2,
            headache: 1,
            nausea: 1,
            'pain in muscles': 1,
            'faster heart rate': 1
        };

        const symptoms = parameters.Symptoms;
        let length = symptoms.length;
        let malariaRisk = 0;

        symptoms.forEach(function(symptom) {
            malariaRisk += symptomScores[symptom];
            let reply;
            if (--length === 0) {
                if (malariaRisk > 6) {
                    reply = response.malariaRisk.level3;
                } else if (malariaRisk > 3) {
                    reply = response.malariaRisk.level2;
                } else {
                    reply = response.malariaRisk.level1;
                }
                done(reply);
            }
        });
    },

    medicineSafeCheck: function(contextParameters, done) {
        const gender = contextParameters.gender;
        let reply;

        if (gender === 'male') {
            reply = response.medicineSafe.gender.male;
        } else {
            reply = response.medicineSafe.gender.female;
        }
        done(reply);
    },

    suggestPreventionTips: function(done) {
        let reply = {
            message: response.preventionTip.message,
            link: [{name: 'StopTheBreed', href: 'prevent/stop-the-breed/game'}, {name: 'StrideAgainstMalaria', href: 'prevent/stride-against-malaria/game'}],
            image: 'assets/img/prevent.png'
        };
        done(reply);
    },

    suggestMedicine: function(done) {
        let reply = {
            message: response.suggestMedicine.message,
            link: [{name: 'MatchTheMeds', href: 'meds-n-labels/activity-1'}, {name: 'MemoryGame', href: 'meds-n-labels/activity-2'}],
            image: 'assets/img/meds.png'
        };
        done(reply);
    },

    medicineSideEffects: function(parameters, done) {
        const medicine = parameters.medicine;
        const medSideEffects = {
            malarone: response.medicineSideEffects.malarone,
            mefloquine: response.medicineSideEffects.mefloquine,
            doxycycline: response.medicineSideEffects.doxycycline
        };

        done(medSideEffects[medicine]);
    },

    introductionMalaria: function(done) {
        let reply = {
            message: response.introductionMalaria.message,
            link: [{name: 'Highlight The Definition', href: 'introduction/activity-1'}, {name: 'An interactive Video', href: 'malaria-101/activity-1-1'}, {name: 'Life cycle of malarial Mosquito', href: 'malaria-101/activity-1-2'}],
            image: 'assets/img/intro.png'
        };
        done(reply);
    },

    onFallback: function(done) {
        //  Reply would be generated by our newly created Bot
        done();
    }
};
